#!/bin/bash
CMD=$1
CMD_FILE=$1.txt
CMD_COUNT=$#
ODOC_PATH=/usr/local/share/odocs
if [ $CMD_COUNT -ne 1 ]; then
	echo "Usage   : $ odoc <command>"
	echo "Example : $ odoc ls"
	echo "Example : $ odoc top"
	exit 0
fi
less $ODOC_PATH/$CMD_FILE
